import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ teams }) {
  const teamArray = teams.data;
  console.log(teamArray);

  return (
    <div className={styles.container}>
      <Head>
        <title>Basketball App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>My Basketball App</h1>
          <div>
            {teamArray.map((teamArr) => (
              <div key={teamArr.id}>
                <h2>{teamArr.full_name}</h2>
                <p>{teamArr.city}</p>
                <p>{teamArr.division}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://www.balldontlie.io/api/v1/teams");
  const data = await response.json();

  return {
    props: { teams: data },
  };
}
